
###服务注册地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
###api网关端口号      
server:
  port: 82
###网关名称  
spring:
  application:
    name: service-zuul
#  cloud:
#    config:
#    ####读取后缀
#      profile: dev
#      ####读取config-server注册地址
#      discovery:
#        service-id: config-server
#        enabled: true
#### 配置网关反向代理 ,可以依据配置文件中心进行集中处理我，地址在https://gitee.com/likangmin/SpringCloudConfig.git
#### http://127.0.0.1/actuator/refresh   进行刷新
zuul:
  routes:
    api-a:
     ### 以 /api-member/访问转发到会员服务
      path: /member/**
      serviceId: app-likangmin-member
#    api-b:
#        ### 以 /api-order/访问转发到订单服务
#      path: /api-order/**
#      serviceId: app-likangmin-order
#    api-c:
#        ### 以 /api-order/访问转发到付款服务
#      path: /api-pay/**
#      serviceId: app-likangmin-pay
###默认服务读取eureka注册服务列表 默认间隔30秒

###开启所有监控中心接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
